# Generated by Django 2.2 on 2020-06-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recolector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recolector',
            name='n_documento_recolector',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
