# Generated by Django 2.2 on 2020-06-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recolector', '0002_recolector_n_documento_recolector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recolector',
            name='calificacion_recolector',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recolector',
            name='cantidad_calificaciones',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recolector',
            name='estado',
            field=models.CharField(blank=True, default='Activo', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='recolector',
            name='suma_calificaciones',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
