# Generated by Django 2.0.2 on 2020-06-23 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comuna', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'ordering': ['nombre_comuna'],
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle_direccion', models.CharField(max_length=50)),
                ('id_comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reciclador.Comuna')),
            ],
            options={
                'verbose_name': 'Direccion',
                'verbose_name_plural': 'Direcciones',
                'ordering': ['calle_direccion'],
            },
        ),
        migrations.CreateModel(
            name='Historial_Reciclador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_finalizado', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historiales',
            },
        ),
        migrations.CreateModel(
            name='Reciclador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_reciclador', models.CharField(max_length=50)),
                ('apellido_reciclador', models.CharField(max_length=50)),
                ('telefono_reciclador', models.CharField(max_length=12)),
                ('correo_reciclador', models.EmailField(max_length=12)),
                ('notificaciones_rechazadas', models.CharField(max_length=12)),
                ('calificacion_recolector', models.FloatField()),
                ('estado', models.IntegerField()),
                ('cantidad_calificaciones', models.FloatField()),
                ('suma_calificaciones', models.FloatField()),
            ],
            options={
                'verbose_name': 'Reciclador',
                'verbose_name_plural': 'Recicladores',
                'ordering': ['nombre_reciclador'],
            },
        ),
        migrations.CreateModel(
            name='Reciclador_Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_direccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reciclador.Direccion')),
                ('id_reciclador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reciclador.Reciclador')),
            ],
        ),
        migrations.AddField(
            model_name='historial_reciclador',
            name='id_reciclador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reciclador.Reciclador'),
        ),
    ]
