# Generated by Django 2.0.2 on 2020-06-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciclador',
            name='estado',
            field=models.CharField(blank=True, default='Activo', max_length=240, null=True),
        ),
    ]
