# Generated by Django 2.0.2 on 2020-06-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclador', '0002_auto_20200627_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciclador',
            name='calificacion_recolector',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reciclador',
            name='cantidad_calificaciones',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reciclador',
            name='notificaciones_rechazadas',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='reciclador',
            name='suma_calificaciones',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
