# Generated by Django 2.0.2 on 2020-06-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclador', '0003_auto_20200627_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciclador',
            name='apellido_reciclador',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reciclador',
            name='correo_reciclador',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reciclador',
            name='telefono_reciclador',
            field=models.CharField(max_length=50),
        ),
    ]
