# Generated by Django 2.2 on 2020-07-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclador', '0005_auto_20200629_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciclador',
            name='calleDireccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CalleDireccion'),
        ),
        migrations.AddField(
            model_name='reciclador',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comuna'),
        ),
        migrations.AddField(
            model_name='reciclador',
            name='contraseña',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contraseña'),
        ),
        migrations.AddField(
            model_name='reciclador',
            name='rut',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rut'),
        ),
    ]
