# Generated by Django 2.2 on 2020-07-23 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reciclador', '0006_auto_20200723_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciclador',
            old_name='rut',
            new_name='rut_reciclador',
        ),
        migrations.RemoveField(
            model_name='reciclador',
            name='calleDireccion',
        ),
        migrations.RemoveField(
            model_name='reciclador',
            name='comuna',
        ),
    ]
