# Generated by Django 2.0.2 on 2020-06-23 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_reporte', models.CharField(max_length=50)),
                ('tipo_reporte', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=300)),
                ('codigo', models.IntegerField()),
                ('fecha_reporte', models.DateField()),
                ('motivo_reporte', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
            },
        ),
        migrations.AddField(
            model_name='solicitud',
            name='id_reporte',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.Reporte'),
        ),
    ]
